### ISSUE TITLE
Wrong init.d on RHEL

### ISSUE THREAD

**Issue by tpbowden** [phlipper/chef-monit#76]
I'm trying to install monit on RHEL (6.4) from binary and I can't figure out how to get it to copy the correct init.d template. I've tried manually and the version in templates/centos works perfectly but for some reason it only copies the version from templates/default. I can't tell if this is a bug or I'm just missing something.

Thanks in advance.

**Comment by rickhull** [comment]
Hi @tpbowden, I joined the team which added the RHEL/CentOS support after they added it.  My guess is that once it was working for CentOS, they stopped caring about the rest of the RHEL family.  A vague memory of looking at the code supports this.  I'll be looking further into this, and I suggest you or anyone else on RHEL proper do the same.

**Comment by tpbowden** [comment]
Is the ohai platform attribute used to decide which directory to take the template from? In which case it just requires either an override or copy/paste job to add more platforms (oracle for example)

**Comment by rickhull** [comment]
@eric239 Do you recall?

**Comment by bcg62** [comment]
At a quick glance it looks like the default recipe does not call _service_configuration which deploys the init.d. 

Try adding it to your run list directly
